from pathlib import Path

for fn in ['ai.js','estudio-arquivo-unico.html']:
    p=Path('/mnt/data/vsync')/fn
    s=p.read_text()
    # key constant
    s=s.replace("  const K_CHAVE_OR = 'openrouter-api-key';\n", "  const K_CHAVE_OR = 'openrouter-api-key';\n  const K_OR_MGMT = 'openrouter-management-key';\n")
    # management state/key after chaves object
    s=s.replace("  const chaves = {\n    groq: S.local.get(K_CHAVE, '') || '',\n    openrouter: S.local.get(K_CHAVE_OR, '') || ''\n  };\n", "  const chaves = {\n    groq: S.local.get(K_CHAVE, '') || '',\n    openrouter: S.local.get(K_CHAVE_OR, '') || ''\n  };\n  let openRouterManagementKey = S.local.get(K_OR_MGMT, '') || '';\n")
    # state provider
    s=s.replace("openrouter: { bloqueadaAte: 0, ultimoSync: 0, status: 'aguardando', limiteRestante: null, uso: null, usoDiario: null, usoMensal: null }", "openrouter: { bloqueadaAte: 0, ultimoSync: 0, ultimoSyncCreditos: 0, status: 'aguardando', limiteRestante: null, uso: null, usoDiario: null, usoMensal: null, saldoConta: null, totalCreditos: null, totalUsoConta: null, erroCreditos: null }")
    # replace sync function block
    old="""  async function sincronizarOpenRouter() {\n    if(!chaves.openrouter) return null;\n    const o=stateProvedor('openrouter');\n    try {\n      const r=await fetch('https://openrouter.ai/api/v1/key',{headers:{Authorization:'Bearer '+chaves.openrouter}});\n      const d=await r.json().catch(()=>null);\n      if(!r.ok) throw new Error((d&&d.error&&d.error.message)||('HTTP '+r.status));\n      const x=d&&d.data||d||{};\n      const limite=numeroOpcional(x.limit);\n      const restante=numeroOpcional(x.limit_remaining);\n      o.ultimoSync=Date.now();\n      o.status='disponivel';\n      o.limite=limite;\n      o.limiteRestante=(limite !== null) ? restante : null;\n      o.temLimiteChave=(limite !== null);\n      o.uso=numeroOpcional(x.usage);\n      o.usoDiario=numeroOpcional(x.usage_daily);\n      o.usoMensal=numeroOpcional(x.usage_monthly);\n      /* Só bloqueia por limite de chave quando o próprio OpenRouter\n         informou que existe um limite. Null = ilimitado. */\n      if(limite !== null && restante !== null && restante <= 0) o.status='esgotado';\n      return x;\n    } catch(e) {\n      o.status='indisponivel';\n      o.erro=String(e.message||e);\n      return null;\n    }\n  }\n"""
    new="""  async function sincronizarOpenRouterCreditos() {\n    const o=stateProvedor('openrouter');\n    if(!openRouterManagementKey) return null;\n    try {\n      const r=await fetch('https://openrouter.ai/api/v1/credits',{headers:{Authorization:'Bearer '+openRouterManagementKey}});\n      const d=await r.json().catch(()=>null);\n      if(!r.ok) throw new Error((d&&d.error&&d.error.message)||('HTTP '+r.status));\n      const x=d&&d.data||d||{};\n      const total=numeroOpcional(x.total_credits);\n      const usado=numeroOpcional(x.total_usage);\n      o.totalCreditos=total;\n      o.totalUsoConta=usado;\n      o.saldoConta=(total!==null && usado!==null) ? Math.max(0,total-usado) : null;\n      o.ultimoSyncCreditos=Date.now();\n      o.erroCreditos=null;\n      if(o.saldoConta!==null && o.saldoConta<=0) o.status='esgotado';\n      else if(o.status!=='esgotado' || o.saldoConta>0) o.status='disponivel';\n      return x;\n    } catch(e) {\n      o.erroCreditos=String(e.message||e);\n      return null;\n    }\n  }\n  async function sincronizarOpenRouter() {\n    if(!chaves.openrouter) return null;\n    const o=stateProvedor('openrouter');\n    try {\n      const r=await fetch('https://openrouter.ai/api/v1/key',{headers:{Authorization:'Bearer '+chaves.openrouter}});\n      const d=await r.json().catch(()=>null);\n      if(!r.ok) throw new Error((d&&d.error&&d.error.message)||('HTTP '+r.status));\n      const x=d&&d.data||d||{};\n      const limite=numeroOpcional(x.limit);\n      const restante=numeroOpcional(x.limit_remaining);\n      o.ultimoSync=Date.now();\n      o.status='disponivel';\n      o.limite=limite;\n      o.limiteRestante=(limite !== null) ? restante : null;\n      o.temLimiteChave=(limite !== null);\n      o.uso=numeroOpcional(x.usage);\n      o.usoDiario=numeroOpcional(x.usage_daily);\n      o.usoMensal=numeroOpcional(x.usage_monthly);\n      if(limite !== null && restante !== null && restante <= 0) o.status='esgotado';\n      await sincronizarOpenRouterCreditos();\n      return x;\n    } catch(e) {\n      o.status='indisponivel';\n      o.erro=String(e.message||e);\n      return null;\n    }\n  }\n  function saldoOpenRouterDisponivel() {\n    const o=stateProvedor('openrouter');\n    const a=numeroOpcional(o.saldoConta);\n    const k=o.temLimiteChave===true ? numeroOpcional(o.limiteRestante) : null;\n    if(a===null && k===null) return null;\n    if(a===null) return k;\n    if(k===null) return a;\n    return Math.min(a,k);\n  }\n"""
    if old not in s:
        print('sync block not found', fn)
    else: s=s.replace(old,new)
    # actual cost from provider
    s=s.replace("    const custo=estimarCusto(pvr,modelo,pin,pout);\n", "    const custoInformado = (pvr==='openrouter') ? numeroOpcional(u.cost) : null;\n    const custo=(custoInformado!==null) ? custoInformado : estimarCusto(pvr,modelo,pin,pout);\n")
    # pre-call account checks after key limit check
    needle="""    if (provedorUsado === 'openrouter' && orStatus.temLimiteChave === true && Number.isFinite(Number(orStatus.limiteRestante)) && Number(orStatus.limiteRestante) < custoEstimado) {\n      const er=new Error(`Saldo/limite real do OpenRouter insuficiente para esta chamada (restante ~US$ ${Number(orStatus.limiteRestante).toFixed(4)}).`); er.cota=true; throw er;\n    }\n"""
    repl=needle+"""    if (provedorUsado === 'openrouter') {\n      const saldoConta=numeroOpcional(orStatus.saldoConta);\n      if (saldoConta !== null && saldoConta <= 0) {\n        const er=new Error('Créditos da conta OpenRouter esgotados. Recarregue a conta para continuar.'); er.cota=true; throw er;\n      }\n      if (saldoConta !== null && custoEstimado > saldoConta) {\n        const er=new Error(`Crédito real da conta OpenRouter insuficiente para esta chamada (saldo ~US$ ${saldoConta.toFixed(4)}).`); er.cota=true; throw er;\n      }\n    }\n"""
    if needle not in s: print('precheck needle missing',fn)
    else: s=s.replace(needle,repl)
    # after successful contabilizar, refresh credits async
    s=s.replace("      if(resp.ok && dados && dados.usage) contabilizar(modelo,dados,ms,provedorUsado);\n", "      if(resp.ok && dados && dados.usage) {\n        contabilizar(modelo,dados,ms,provedorUsado);\n        if(provedorUsado==='openrouter') void sincronizarOpenRouterCreditos();\n      }\n")
    # save management function before salvarCfg
    marker="""  function salvarCfg(novaChave, pensamento, producao, limiteTokensDia, orcamentoUSD, limiteDiarioUSD, diarioAutomatico, modoOrcamento, roteamento) {\n"""
    add="""  function salvarChaveGerenciamentoOpenRouter(chaveMgmt) {\n    const k=String(chaveMgmt||'').trim();\n    if(k && !/^sk-or-[A-Za-z0-9_-]{10,}$/.test(k)) throw new Error('A chave de gerenciamento do OpenRouter parece inválida.');\n    openRouterManagementKey=k;\n    if(k) S.local.set(K_OR_MGMT,k); else S.local.del(K_OR_MGMT);\n    const o=stateProvedor('openrouter');\n    o.saldoConta=null; o.totalCreditos=null; o.totalUsoConta=null; o.erroCreditos=null;\n    return sincronizarOpenRouterCreditos();\n  }\n\n"""+marker
    if marker not in s: print('savecfg marker missing',fn)
    else: s=s.replace(marker,add)
    # orcamento return add provider balance fields
    oldret="""tier:cfg.tier,roteamento:cfg.roteamento,limiteTokensDia:cfg.limiteTokensDia};\n"""
    newret="""tier:cfg.tier,roteamento:cfg.roteamento,limiteTokensDia:cfg.limiteTokensDia,openrouterSaldo:stateProvedor('openrouter').saldoConta,openrouterLimiteChave:stateProvedor('openrouter').limiteRestante,openrouterSaldoEfetivo:saldoOpenRouterDisponivel(),openrouterManagementConfigured:Boolean(openRouterManagementKey),openrouterSync:stateProvedor('openrouter').ultimoSyncCreditos};\n"""
    if oldret not in s: print('return missing',fn)
    else: s=s.replace(oldret,newret)
    # export
    s=s.replace("salvarCfg, salvarChaves, limiteTokensDia,\n", "salvarCfg, salvarChaves, salvarChaveGerenciamentoOpenRouter, limiteTokensDia,\n")
    s=s.replace("sincronizarFornecedor: sincronizarOpenRouter,\n", "sincronizarFornecedor: sincronizarOpenRouter, sincronizarCreditosOpenRouter: sincronizarOpenRouterCreditos,\n")
    s=s.replace("statusFornecedores: () => ({ groq: stateProvedor('groq'), openrouter: stateProvedor('openrouter'), roteamento: cfg.roteamento }),\n", "statusFornecedores: () => ({ groq: stateProvedor('groq'), openrouter: stateProvedor('openrouter'), roteamento: cfg.roteamento, openrouterSaldo: saldoOpenRouterDisponivel(), openrouterManagementConfigured: Boolean(openRouterManagementKey) }),\n")
    p.write_text(s)
